version: '2'

services:

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: .docker/nginx.dockerfile
  #   links:
  #     - node1:node1
  #     - node2:node2
  #     - node3:node3
  #   depends_on:
  #     - node1
  #     - node2
  #     - node3
  #   ports:
  #     - "9999:8080"
  #   networks:
  #     - app-network

  node1:
    container_name: rest_api
    build:
      context: .
      dockerfile: Dockerfile
    # command: ./node_modules/.bin/babel-node ./dist/bin/www
    working_dir: /usr/src/api
    volumes:
      - ./upload:/usr/src/api/uploads
      - ./node_modules:/usr/src/api/node_modules
    ports:
      - "4000"
    env_file:
      - .env.production
    environment:
      - INSTANCE=node1
      - VIRTUAL_HOST=prototype-back.iammoon.xyz
    networks:
      - app-network


networks:
  app-network:
    external:
      name: nginx-proxy

